class CHATGPTConstants:
    COMPLETION_ENGINE = "text-davinci-003"
    CHAT_COMPLETION_ENGINE = "text-davinci-003"
    COMPLETION_MAX_TOKENS = 2500
    COMPLETION_TEMPERATURE = 0.3
    CHAT_COMPLETION_MAX_TOKENS = 2500
    CHAT_COMPLETION_TEMPERATURE = 0.3

